<a href="https://colab.research.google.com/github/faisu6339-glitch/LLMs/blob/main/Self_Attention_Mechanism.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Self-Attention Mechanism in Large Language Models (LLMs)

Self-attention is a core component of the Transformer architecture, which revolutionized natural language processing and is the foundation of most modern Large Language Models (LLMs). It allows the model to weigh the importance of different words in an input sequence when processing each word, thus capturing long-range dependencies and contextual relationships.

Here's a breakdown of how it works:

1.  **Input Representation:**
    *   Each word (or token) in the input sequence is first converted into a numerical representation called an **embedding vector**. These embeddings capture the semantic meaning of the words.
    *   **Positional Encodings** are added to these embeddings to inject information about the word's position in the sequence, as the self-attention mechanism itself is permutation-invariant (doesn't inherently understand order).

2.  **Query, Key, and Value Vectors (Q, K, V):**
    *   For each input embedding (representing a word), three distinct vectors are created: a **Query (Q)**, a **Key (K)**, and a **Value (V)** vector.
    *   These are generated by multiplying the input embedding by three different weight matrices (W_Q, W_K, W_V) that are learned during training. These matrices project the word embedding into different representation spaces.

3.  **Calculating Attention Scores:**
    *   For each word in the sequence (the "query" word), we want to determine how much attention it should pay to every other word in the sequence (the "key" words).
    *   This is done by calculating the **dot product** between the Query vector of the current word and the Key vectors of all other words (including itself). A higher dot product indicates greater similarity or relevance.
    *   The results are then divided by the square root of the dimension of the key vectors (d_k). This is a scaling factor that helps stabilize gradients during training.

4.  **Softmax Normalization:**
    *   The scaled attention scores are then passed through a **softmax function**. This normalizes the scores such that they sum to 1 and can be interpreted as probabilities or weights.
    *   These softmax outputs represent how much each word in the input sequence contributes to the representation of the current word.

5.  **Weighted Sum of Value Vectors:**
    *   Finally, the softmax scores (attention weights) are multiplied by their corresponding **Value (V)** vectors. All these weighted Value vectors are then summed up.
    *   This weighted sum creates a new vector for the current word, which is a rich contextual representation that incorporates information from all other words in the sequence, weighted by their relevance to the current word.

**Multi-Head Attention:**

LLMs typically use **Multi-Head Attention**. Instead of just one set of Q, K, V matrices, they use multiple sets (e.g., 8 or 12 "heads"). Each head performs the self-attention calculation independently, learning to focus on different aspects of the relationships between words. The outputs from all heads are then concatenated and linearly transformed to produce the final output for each word.

**Why is Self-Attention Powerful for LLMs?**

*   **Captures Long-Range Dependencies:** Unlike traditional RNNs which struggle with long sequences, self-attention can directly connect any two words in a sentence, regardless of their distance.
*   **Parallelization:** The computations for each word's attention can be performed in parallel, making it highly efficient for training on large datasets.
*   **Contextual Understanding:** It allows the model to create highly context-aware representations of words, understanding how a word's meaning changes based on its surrounding words.

### Self-Attention vs. Multi-Head Attention

While closely related, **Self-Attention** and **Multi-Head Attention** are not the same; Multi-Head Attention is an extension and refinement of the basic self-attention mechanism.

**1. Self-Attention (as described previously):**

*   **Core Idea:** It allows each word in a sequence to attend to every other word in the same sequence, producing a weighted sum of their value vectors based on their relevance (calculated via query-key similarities).
*   **Single Set of Projections:** In its basic form, self-attention uses one set of learned weight matrices (W_Q, W_K, W_V) to project the input embeddings into Query, Key, and Value vectors.
*   **Single Contextual Representation:** It generates a single contextual representation for each word, incorporating information from the entire sequence.
*   **Focus:** It allows the model to capture a single type of relationship or dependency within the sequence.

**2. Multi-Head Attention:**

*   **Core Idea:** It runs the self-attention mechanism multiple times in parallel, each with different, independently learned linear projection matrices (W_Q_i, W_K_i, W_V_i for each head `i`).
*   **Multiple "Heads":** The input embeddings are first projected `h` times (where `h` is the number of heads), creating `h` different sets of Query, Key, and Value vectors. Each of these sets then independently performs the self-attention calculation.
*   **Diverse Relational Views:** Each "head" can learn to focus on different aspects of the input sequence or different types of relationships. For example, one head might learn to identify syntactic dependencies, while another might focus on semantic similarities.
*   **Concatenation and Final Projection:** The outputs from all `h` individual self-attention heads are then concatenated. This combined vector is then linearly projected (using another learned weight matrix W_O) to produce the final output, which has the desired dimensionality.
*   **Enhanced Representational Power:** By combining insights from multiple attention "perspectives," Multi-Head Attention allows the model to capture a richer and more comprehensive understanding of the relationships within the sequence.
*   **Example Analogy:** Think of a team of experts analyzing a document. A single self-attention head is like one expert focusing on one aspect (e.g., grammar). Multi-head attention is like having several experts, each specializing in different aspects (grammar, tone, facts, sentiment), and then combining their analyses to get a more complete understanding.

**In summary:**

*   **Self-Attention** is the fundamental mechanism that allows words to weigh the importance of other words in a sequence.
*   **Multi-Head Attention** is an architecture that parallelizes and enhances self-attention by allowing the model to simultaneously attend to different aspects of the information from different representation subspaces, leading to a more robust and powerful contextual understanding.

### Why Do We Need Self-Attention?

Before the advent of self-attention (and the Transformer architecture), recurrent neural networks (RNNs) and their variants like LSTMs and GRUs were the state-of-the-art for sequence data. However, they had several inherent limitations that self-attention elegantly addresses:

1.  **Capturing Long-Range Dependencies:**
    *   **RNN Problem:** RNNs process sequences token by token, maintaining a 'hidden state' that is updated at each step. Information from early parts of a long sequence tends to gradually fade or be 'forgotten' by the time the model reaches later parts. This is known as the **long-term dependency problem**.
    *   **Self-Attention Solution:** Self-attention allows the model to directly compute the relationships between any two words in a sequence, regardless of their distance. This direct connection makes it much more effective at capturing dependencies between words that are far apart, which is crucial for understanding context in long sentences or documents.

2.  **Parallelization and Training Speed:**
    *   **RNN Problem:** The sequential nature of RNNs makes them inherently difficult to parallelize during training. Each step depends on the output of the previous step, meaning computations must largely be performed one after another.
    *   **Self-Attention Solution:** In self-attention, the dependencies between all words are calculated simultaneously (or in parallel) through matrix multiplications. This parallelizability allows for much faster training on modern hardware (GPUs, TPUs), which is essential for training the massive LLMs we see today.

3.  **Fixed-Size Context Window (CNNs for sequences):**
    *   **CNN Problem (if used for sequences):** While convolutional neural networks (CNNs) can process sequences in parallel, they typically have a fixed-size filter (kernel), meaning they can only capture local dependencies within a defined window. To capture longer-range dependencies, you'd need many layers or very large filters, which is inefficient.
    *   **Self-Attention Solution:** Self-attention effectively has a dynamic, non-local 'receptive field' for each word, allowing it to consider the entire sequence to determine context, without the limitations of a fixed window size.

4.  **Interpretability (to some extent):**
    *   While LLMs are still largely black boxes, attention weights can offer some insights into which parts of the input the model is focusing on when making a decision or generating text. This can provide a degree of interpretability that is harder to achieve with other architectures.

In essence, self-attention provides a more flexible, efficient, and powerful mechanism for modeling relationships within sequences, overcoming the limitations of previous architectures and enabling the creation of much larger and more capable language models.

In [1]:
import numpy as np

def softmax(x):
    """Compute softmax values for each row of x."""
    e_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return e_x / np.sum(e_x, axis=-1, keepdims=True)

def self_attention(query, key, value, mask=None):
    """
    Simple implementation of scaled dot-product self-attention.

    Args:
        query (np.array): Query matrix (batch_size, seq_len, d_k).
        key (np.array): Key matrix (batch_size, seq_len, d_k).
        value (np.array): Value matrix (batch_size, seq_len, d_v).
        mask (np.array, optional): Optional mask for attention scores.

    Returns:
        np.array: Contextualized output (batch_size, seq_len, d_v).
        np.array: Attention weights (batch_size, seq_len, seq_len).
    """
    # Calculate query and key dimensions
    d_k = query.shape[-1]

    # 1. Compute attention scores: Q * K^T
    # (batch_size, seq_len, d_k) @ (batch_size, d_k, seq_len) -> (batch_size, seq_len, seq_len)
    scores = np.matmul(query, key.transpose(0, 2, 1))

    # 2. Scale the scores
    scores = scores / np.sqrt(d_k)

    # 3. Apply mask (for preventing attention to future tokens or padding)
    if mask is not None:
        scores = scores + (mask * -1e9) # Adding a very large negative number to masked positions

    # 4. Apply softmax to get attention weights
    attention_weights = softmax(scores)

    # 5. Multiply weights by Value matrix
    # (batch_size, seq_len, seq_len) @ (batch_size, seq_len, d_v) -> (batch_size, seq_len, d_v)
    output = np.matmul(attention_weights, value)

    return output, attention_weights

# --- Example Usage ---

# Define input sequence (e.g., 3 words, each with an embedding dimension of 4)
# batch_size = 1, seq_len = 3, embedding_dim = 4
input_sequence = np.array([[
    [1.0, 0.5, 0.2, 0.8],  # Word 1 embedding
    [0.1, 0.9, 0.3, 0.7],  # Word 2 embedding
    [0.6, 0.4, 1.0, 0.2]   # Word 3 embedding
]])

print("Input Sequence Shape:", input_sequence.shape)
print("Input Sequence:\n", input_sequence)

# For simplicity, let's assume Query, Key, and Value matrices are derived
# directly from the input sequence through linear transformations.
# In a real model, these would be learned weight matrices.

# Let's say d_k = d_v = embedding_dim
d_model = input_sequence.shape[-1]

# Simple linear projections (identity for demonstration, normally learned W_Q, W_K, W_V)
# Q = input_sequence @ W_Q
# K = input_sequence @ W_K
# V = input_sequence @ W_V

# For this example, let's just make Q, K, V similar to input for clarity
query = input_sequence
key = input_sequence
value = input_sequence

# Compute self-attention
output_context, attention_weights = self_attention(query, key, value)

print("\nOutput Contextualized Embeddings Shape:", output_context.shape)
print("Output Contextualized Embeddings:\n", output_context)

print("\nAttention Weights Shape:", attention_weights.shape)
print("Attention Weights (rows sum to 1):\n", attention_weights)

# Interpretation of attention_weights:
# attention_weights[0, i, j] shows how much attention word i pays to word j.
# For example, attention_weights[0, 0, 1] is how much Word 1 attends to Word 2.
# The diagonal elements (e.g., [0, 0, 0]) show how much a word attends to itself.

print("\nExample: How much does Word 1 attend to other words?")
print(f"  Word 1 -> Word 1: {attention_weights[0, 0, 0]:.4f}")
print(f"  Word 1 -> Word 2: {attention_weights[0, 0, 1]:.4f}")
print(f"  Word 1 -> Word 3: {attention_weights[0, 0, 2]:.4f}")

Input Sequence Shape: (1, 3, 4)
Input Sequence:
 [[[1.  0.5 0.2 0.8]
  [0.1 0.9 0.3 0.7]
  [0.6 0.4 1.  0.2]]]

Output Contextualized Embeddings Shape: (1, 3, 4)
Output Contextualized Embeddings:
 [[[0.62456076 0.58691725 0.45916488 0.59839526]
  [0.54596336 0.62191829 0.46771062 0.58979994]
  [0.59015156 0.57207493 0.54495613 0.53430142]]]

Attention Weights Shape: (1, 3, 3)
Attention Weights (rows sum to 1):
 [[[0.42295601 0.2892433  0.28780069]
  [0.3357633  0.37668392 0.28755278]
  [0.32445298 0.27925926 0.39628776]]]

Example: How much does Word 1 attend to other words?
  Word 1 -> Word 1: 0.4230
  Word 1 -> Word 2: 0.2892
  Word 1 -> Word 3: 0.2878


In [2]:
import numpy as np

# Q, K, V
Q = np.array([
    [1, 0],
    [0, 1],
    [1, 1]
])

K = np.array([
    [1, 0],
    [1, 1],
    [0, 1]
])

V = np.array([
    [10, 20],
    [30, 40],
    [50, 60]
])

# Step 1: QK^T
scores = Q @ K.T

print("Scores:")
print(scores)

# Step 2: Scale
d_k = K.shape[-1]
scores = scores / np.sqrt(d_k)

# Step 3: Softmax
def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return exp_x / np.sum(exp_x, axis=-1, keepdims=True)

attention_weights = softmax(scores)

print("\nAttention Weights:")
print(attention_weights)

# Step 4: Weighted sum of values
output = attention_weights @ V

print("\nOutput:")
print(output)

Scores:
[[1 1 0]
 [0 1 1]
 [1 2 1]]

Attention Weights:
[[0.40111209 0.40111209 0.19777581]
 [0.19777581 0.40111209 0.40111209]
 [0.24825508 0.50348984 0.24825508]]

Output:
[[25.93327444 35.93327444]
 [34.06672556 44.06672556]
 [30.         40.        ]]


In [3]:
scores = Q @ K.T

scores = scores / np.sqrt(d_k)

attention_weights = softmax(scores)

output = attention_weights @ V

# Implementing Q, K and V

In [4]:
import numpy as np

np.random.seed(42)

# Input embeddings
X = np.random.randn(4, 6)

# Weight matrices
W_Q = np.random.randn(6, 4)
W_K = np.random.randn(6, 4)
W_V = np.random.randn(6, 4)

# Create Q, K, V
Q = X @ W_Q
K = X @ W_K
V = X @ W_V

print("Q shape:", Q.shape)
print("K shape:", K.shape)
print("V shape:", V.shape)

Q shape: (4, 4)
K shape: (4, 4)
V shape: (4, 4)
